/*
 * CthulhuMud
 */

#define OBJ_VNUM_RITUAL   20043

/* functions needed by all magic*.c files */
/* all of these are found in magic.c */

void    	say_spell       	(CHAR_DATA *ch, char *text );
int 	skill_lookup	(const char *name );
int 	slot_lookup	(int slot );
bool 	saves_spell	(int level, CHAR_DATA *victim );
void	raw_kill		(CHAR_DATA *victim, bool corpse ) ;
int  	wild_magic	(CHAR_DATA *ch, int efn, int spn);
void 	do_duel_prompt	(CHAR_DATA *ch, CHAR_DATA *victim);
void 	do_duel_finish	(CHAR_DATA *ch, CHAR_DATA *victim, CHAR_DATA *winner, CHAR_DATA *loser, char *msg, char *msg2, char *msg3 );

#define DUEL_SPEED	3
#define DUEL_COST	10

/*
 * Spell functions.
 * Defined in magic.c.
 */
DECLARE_SPELL_FUN(spell_null);
DECLARE_SPELL_FUN(spell_brand);
DECLARE_SPELL_FUN(spell_mask_self );
DECLARE_SPELL_FUN(spell_incognito);
DECLARE_SPELL_FUN(spell_absorb_magic);
DECLARE_SPELL_FUN(spell_acid_breath);
DECLARE_SPELL_FUN(spell_age); 
DECLARE_SPELL_FUN(spell_youth);
DECLARE_SPELL_FUN(spell_animate); 
DECLARE_SPELL_FUN(spell_mummify); 
DECLARE_SPELL_FUN(spell_lich); 
DECLARE_SPELL_FUN(spell_summon_familier); 
DECLARE_SPELL_FUN(spell_summon_spirit); 
DECLARE_SPELL_FUN(spell_elder_watcher); 
DECLARE_SPELL_FUN(spell_soul_blade);
DECLARE_SPELL_FUN(spell_minor_creation);
DECLARE_SPELL_FUN(spell_create_seed);
DECLARE_SPELL_FUN(spell_greater_creation);
DECLARE_SPELL_FUN(spell_psi_twister); 
DECLARE_SPELL_FUN(spell_exorcism);
DECLARE_SPELL_FUN(spell_acid_blast);
DECLARE_SPELL_FUN(spell_armor);
DECLARE_SPELL_FUN(spell_bless);
DECLARE_SPELL_FUN(spell_relax	);
DECLARE_SPELL_FUN(spell_blindness);
DECLARE_SPELL_FUN(spell_burden_of_blubber);
DECLARE_SPELL_FUN(spell_burning_hands);
DECLARE_SPELL_FUN(spell_burning_thirst);
DECLARE_SPELL_FUN(spell_call_lightning	);
DECLARE_SPELL_FUN(spell_calm);
DECLARE_SPELL_FUN(spell_cancellation);
DECLARE_SPELL_FUN(spell_cause_critical	);
DECLARE_SPELL_FUN(spell_cause_death);
DECLARE_SPELL_FUN(spell_cause_light);
DECLARE_SPELL_FUN(spell_cause_serious);
DECLARE_SPELL_FUN(spell_change_sex);
DECLARE_SPELL_FUN(spell_chain_lightning);
DECLARE_SPELL_FUN(spell_chaos);
DECLARE_SPELL_FUN(spell_charm_person);
DECLARE_SPELL_FUN(spell_lesser_possession);
DECLARE_SPELL_FUN(spell_greater_possession);
DECLARE_SPELL_FUN(spell_chill_touch);
DECLARE_SPELL_FUN(spell_colour_spray);
DECLARE_SPELL_FUN(spell_mage_light);
DECLARE_SPELL_FUN(spell_continual_light);
DECLARE_SPELL_FUN(spell_control_weather);
DECLARE_SPELL_FUN(spell_create_buffet); 
DECLARE_SPELL_FUN(spell_create_food);
DECLARE_SPELL_FUN(spell_create_spring	);
DECLARE_SPELL_FUN(spell_create_water	);
DECLARE_SPELL_FUN(spell_create_potion);
DECLARE_SPELL_FUN(spell_cure_blindness);
DECLARE_SPELL_FUN(spell_cure_critical);
DECLARE_SPELL_FUN(spell_transformation);
DECLARE_SPELL_FUN(spell_cure_disease);
DECLARE_SPELL_FUN(spell_cure_light);
DECLARE_SPELL_FUN(spell_cure_poison);
DECLARE_SPELL_FUN(spell_hallucinate);
DECLARE_SPELL_FUN(spell_cure_serious);
DECLARE_SPELL_FUN(spell_curse);
DECLARE_SPELL_FUN(spell_demonfire);
DECLARE_SPELL_FUN(spell_detect_evil);
DECLARE_SPELL_FUN(spell_detect_good);
DECLARE_SPELL_FUN(spell_detect_hidden);
DECLARE_SPELL_FUN(spell_detect_invis);
DECLARE_SPELL_FUN(spell_detect_magic);
DECLARE_SPELL_FUN(spell_detect_poison);
DECLARE_SPELL_FUN(spell_dispel_evil);
DECLARE_SPELL_FUN(spell_dispel_good);
DECLARE_SPELL_FUN(spell_dispel_magic);
DECLARE_SPELL_FUN(spell_earthquake);
DECLARE_SPELL_FUN(spell_enchant_armor);
DECLARE_SPELL_FUN(spell_enchant_weapon);
DECLARE_SPELL_FUN(spell_personalize_weapon);
DECLARE_SPELL_FUN(spell_animate_weapon);
DECLARE_SPELL_FUN(spell_enchanted_sleep);
DECLARE_SPELL_FUN(spell_energy_drain);
DECLARE_SPELL_FUN(spell_entropy); 
DECLARE_SPELL_FUN(spell_faerie_fire);
DECLARE_SPELL_FUN(spell_faerie_fog);
DECLARE_SPELL_FUN(spell_fear);
DECLARE_SPELL_FUN(spell_fire_breath);
DECLARE_SPELL_FUN(spell_fireball);
DECLARE_SPELL_FUN(spell_flamestrike);
DECLARE_SPELL_FUN(spell_fly);
DECLARE_SPELL_FUN(spell_free_grog);
DECLARE_SPELL_FUN(spell_frenzy);
DECLARE_SPELL_FUN(spell_frost_breath);
DECLARE_SPELL_FUN(spell_general_purpose);
DECLARE_SPELL_FUN(spell_gas_breath);
DECLARE_SPELL_FUN(spell_gate);
DECLARE_SPELL_FUN(spell_ghastly_sobriety);
DECLARE_SPELL_FUN(spell_giant_strength);
DECLARE_SPELL_FUN(spell_gnawing_hunger);
DECLARE_SPELL_FUN(spell_harm);
DECLARE_SPELL_FUN(spell_fatigue);
DECLARE_SPELL_FUN(spell_haste);
DECLARE_SPELL_FUN(spell_heal	);
DECLARE_SPELL_FUN(spell_restore_limb);
DECLARE_SPELL_FUN(spell_high_explosive);
DECLARE_SPELL_FUN(spell_holy_word);
DECLARE_SPELL_FUN(spell_identify);
DECLARE_SPELL_FUN(spell_infravision);
DECLARE_SPELL_FUN(spell_invis);
DECLARE_SPELL_FUN(spell_know_alignment);
DECLARE_SPELL_FUN(spell_lightning_bolt);
DECLARE_SPELL_FUN(spell_lightning_breath);
DECLARE_SPELL_FUN(spell_locate_object	);
DECLARE_SPELL_FUN(spell_magic_missile);
DECLARE_SPELL_FUN(spell_mass_healing	);
DECLARE_SPELL_FUN(spell_mass_invis);
DECLARE_SPELL_FUN(spell_mute);
DECLARE_SPELL_FUN(spell_silence);
DECLARE_SPELL_FUN(spell_darkness);
DECLARE_SPELL_FUN(spell_negate_alignment);
DECLARE_SPELL_FUN(spell_pass_door);
DECLARE_SPELL_FUN(spell_plague);
DECLARE_SPELL_FUN(spell_pestillence);
DECLARE_SPELL_FUN(spell_poison);
DECLARE_SPELL_FUN(spell_portal);
DECLARE_SPELL_FUN(spell_destroy_portal);
DECLARE_SPELL_FUN(spell_protection_evil);
DECLARE_SPELL_FUN(spell_protection_good);
DECLARE_SPELL_FUN(spell_refresh);
DECLARE_SPELL_FUN(spell_regeneration);
DECLARE_SPELL_FUN(spell_remove_curse);
DECLARE_SPELL_FUN(spell_remove_fear);
DECLARE_SPELL_FUN(spell_remove_invis);
DECLARE_SPELL_FUN(spell_recurring_dream);
DECLARE_SPELL_FUN(spell_rude_awakening);
DECLARE_SPELL_FUN(spell_sanctuary);
DECLARE_SPELL_FUN(spell_shocking_grasp);
DECLARE_SPELL_FUN(spell_shield);
DECLARE_SPELL_FUN(spell_sleep);
DECLARE_SPELL_FUN(spell_slender_lines);
DECLARE_SPELL_FUN(spell_hard_skin);
DECLARE_SPELL_FUN(spell_summon);
DECLARE_SPELL_FUN(spell_teleport);
DECLARE_SPELL_FUN(spell_true_dreaming);
DECLARE_SPELL_FUN(spell_ventriloquate);
DECLARE_SPELL_FUN(spell_vocalize);
DECLARE_SPELL_FUN(spell_weaken);
DECLARE_SPELL_FUN(spell_word_of_recall);
DECLARE_SPELL_FUN(spell_water_breathing);
DECLARE_SPELL_FUN(spell_universality);
DECLARE_SPELL_FUN(spell_permanence);
DECLARE_SPELL_FUN(spell_consistence);
DECLARE_SPELL_FUN(spell_mana_transfer);
DECLARE_SPELL_FUN(spell_consecrate_doll);
DECLARE_SPELL_FUN(spell_wrath_cthuga);
DECLARE_SPELL_FUN(spell_aura);
DECLARE_SPELL_FUN(spell_cause_riot);
DECLARE_SPELL_FUN(spell_trance);
DECLARE_SPELL_FUN(spell_mind_meld);
DECLARE_SPELL_FUN(spell_psychic_anchor);
DECLARE_SPELL_FUN(spell_fire_shield);
DECLARE_SPELL_FUN(spell_frost_shield);
DECLARE_SPELL_FUN(spell_lightning_shield);
DECLARE_SPELL_FUN(spell_protection_fire);
DECLARE_SPELL_FUN(spell_protection_frost);
DECLARE_SPELL_FUN(spell_protection_lightning);
DECLARE_SPELL_FUN(spell_personalize_portal);
DECLARE_SPELL_FUN(spell_slow);
DECLARE_SPELL_FUN(spell_globe_of_protection);
DECLARE_SPELL_FUN(spell_bestow_blessing);
DECLARE_SPELL_FUN(spell_metamorphosis);
DECLARE_SPELL_FUN(spell_mortalize);
DECLARE_SPELL_FUN(spell_call_pet);
DECLARE_SPELL_FUN(spell_curse_mummy);
DECLARE_SPELL_FUN(spell_enclosure);
DECLARE_SPELL_FUN(spell_recharge);
DECLARE_SPELL_FUN(spell_create_figurine);
DECLARE_SPELL_FUN(spell_elder_shield);
DECLARE_SPELL_FUN(spell_telekinesis);
DECLARE_SPELL_FUN(spell_duel);
DECLARE_SPELL_FUN(spell_heat_weapon);
DECLARE_SPELL_FUN(spell_agony);
DECLARE_SPELL_FUN(spell_true_sight);
DECLARE_SPELL_FUN(spell_drain_vitality);
DECLARE_SPELL_FUN(spell_confuse_hunters);
DECLARE_SPELL_FUN(spell_farsight);
DECLARE_SPELL_FUN(spell_change_size);
DECLARE_SPELL_FUN(spell_astral_walk);
DECLARE_SPELL_FUN(spell_astral_blast);
DECLARE_SPELL_FUN(spell_oracle);
DECLARE_SPELL_FUN(spell_doppelganger);
DECLARE_SPELL_FUN(spell_blade_affect);
DECLARE_SPELL_FUN(spell_release_mana);
DECLARE_SPELL_FUN(spell_store_mana);
DECLARE_SPELL_FUN(spell_asceticism);
DECLARE_SPELL_FUN(spell_antipsychotica);
